import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Oswald } from "next/font/google";
import "./globals.css";
import { Handshake } from "lucide-react";
import WhatsappBtn from "@/components/ui/whatsapp-btn";
import { Logo, Navbar } from "./components";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  subsets: ["latin"],
});
const oswald = Oswald({
  subsets: ["latin"],
  weight:['400', "500", "600", "700"],
  variable:'--font-oswald'
});

export const metadata: Metadata = {
  title: "Trabi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.className} ${oswald.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <>
          <Navbar
            logo={
              <div className="flex items-center">
                <div className="border-2 rounded-full">
                  <Logo onlyLogo />
                </div>
                <div className="ml-2">
                  <div className="text-lg  font-semibold "> Trabi.</div>
                </div>
              </div>
            }
            navigation={[
              { label: "Explore", href: "/travel/destinations" },
              { label: "Trips", href: "/travel/search" },
              { label: "Agencies", href: "/travel/travel-agencies" },
              { label: "Host a trip", href: "/travel/host-a-trip" },
            ]}
            login={{ label: "Log in", href: "/login" }}
            cta={{
              label: "Join Us",
              href: "/register",
              icon: (
                <Handshake
                  className="mr-1 size-4 text-theme-lime"
                  strokeWidth={3}
                />
              ),
            }}
          />
          {children}
          <WhatsappBtn />
        </>
      </body>
    </html>
  );
}
